### ISSUE TITLE
[ Solved ] Codes not being sent on example site - Sendiblue email Issue.

### ISSUE THREAD

**Issue by cayblood** [dev-xo/remix-auth-otp#10]
Love the project. Thanks for building this. I'm trying to test it, but unable to get a code generated on [your example site](https://otp-stack.fly.dev/).

**Comment by dev-xo** [comment]
Hello @cayblood .
Gonna look into it, but that probably will be the Email Service provider.

Also worked for me, give it a try in a few minutes.
![Screen Shot 2023-02-08 at 23 56 50](https://user-images.githubusercontent.com/82425492/217670316-cf109f55-48aa-4006-8919-912d41664c4c.png)

**Comment by dev-xo** [comment]
Notice me if you need help with anything else, and sorry for the inconveniences!
Nothing  I can do in this case _(Give it a try a few moments later!)_

**Comment by dev-xo** [comment]
Also give it a try cleaning the cookies / session @cayblood !
