### ISSUE TITLE
Block generate infinity codes

### ISSUE THREAD

**Issue by siimaoo** [dev-xo/remix-auth-otp#11]
I think that this lib need a mechanism builtin to protect against create infinity codes.

If defined that the code expires after five minutes, the user only can generate new code after old code expires, this behavior will prevent some abuses.

It's possible to implement this behavior built in?

**Comment by w00fz** [comment]
Agreed, 
I also think we need a cleanup method. I did  try cleaning up in my verify function to remove from the db the inactive codes but didn’t quite work and I didn’t investigate it further.

**Comment by dev-xo** [comment]
Agree with you @w00fz.
I also think we need some cleanup function.

The code is automatically invalidated on certain cases, but in most of them (if not all), requires the user to input the code.
Adding a cleanup function will probably increase the complexity of setting-up the strategy.

There is already 4 main functions that are required for the strategy to work properly.
So I don't know. 

If you have an idea or if you really think we can improve or work on this, im up for it @w00fz.

**Comment by dev-xo** [comment]
Closing this for now, the Issue title does not help, and I think @w00fz already solved your issue @siimaoo.
Feel free to ask any other question or propose anything you can think could improve the library.

**Comment by siimaoo** [comment]
well, I think you miss undestand.

go to: https://otp-stack.fly.dev/
click in login button
put your email
and click in request new code and click again and again and again.

the user can create infinity codes without a countdown.

@dev-xo  @w00fz

**Comment by dev-xo** [comment]
Hello again @siimaoo 
You have to know that the old code will be invalidated automatically on your database, every time you request a new code.

Maybe we can add a feature to not spam the button? Yes, but that could be easily managed on the client side by the developer.
