### ISSUE TITLE
successRedirect type is not required but throw error if undefined

### ISSUE THREAD

**Issue by siimaoo** [dev-xo/remix-auth-otp#12]
![CleanShot 2023-02-09 at 20 20 27](https://user-images.githubusercontent.com/34813589/217961160-3279705e-998a-4cca-836b-38c77d0bf1a9.png)
![CleanShot 2023-02-09 at 20 21 38](https://user-images.githubusercontent.com/34813589/217961225-8c2b26b5-b977-4d10-b83b-c3ef16055aa4.png)

**Comment by siimaoo** [comment]
I know that I can use a try/catch but this seems a incorrect behavior

**Comment by dev-xo** [comment]
Can you show a full example of your implementation?
`successRedirect` it's required for the Strategy to properly work. It will redirect you to the provided validate route / form.
You will get that error if not provided.

Please, check the documentation and feel free to follow the [Example Code](https://github.com/dev-xo/otp-stack) implementation.
You should not get any kind of error when implemented correctly.

**Comment by dev-xo** [comment]
About the type, I think you are right.
Will be fixed soon.

**Comment by dev-xo** [comment]
Nothing else to say @siimaoo ?

Thread gonna be removed in the next hours.
Feel free to ask anything else.
