### ISSUE TITLE
[ Help ] Getting "invalid email" error on email with "+" sign.

### ISSUE THREAD

**Issue by CSFlorin** [dev-xo/remix-auth-otp#18]
Trying to use an email like test+1@gmail.com and the code generates fine but when I enter the code, it gives the error "invalid email". I don't have any code that checks this so I think it is the library. Any idea?

**Comment by dev-xo** [comment]
Hello @CSFlorin.

No idea about what could be going wrong. 
Does the console throw you some explicit error?

Could be the email validation, but never experienced this before.
Should be working fine.

Please, give me more info about this, maybe we can do something to look into it deeply.

**Comment by dev-xo** [comment]
Thread gonna be closed in the next 24 hours, no response from original poster.
