### ISSUE TITLE
Suggestions for debugging error: "'Magic Link does not match the expected Signature.'"?

### ISSUE THREAD

**Issue by andersr** [dev-xo/remix-auth-otp#19]
Hi, I added your OTP strategy and I think I followed all the instructions exactly.  However, when I click on the magic link sent in the email, I get the message 'Magic Link does not match the expected Signature.'  - I've been through the code several times and do not see any issues. I also looked in the [source code](https://github.com/dev-xo/remix-auth-otp/blob/3e78ed680e12096445c7be4c1ecc96ee9b31de19/src/index.ts#L664) where the error is thrown and did not see an obvious way to debug. Any suggestions?  Happy to create a reproduction but wanted to first see if there might be an obvious thing to check. Thanks!

**Comment by dev-xo** [comment]
Hello @andersr. This is the v2 of `remix-auth-otp` v3 gonna be released in a few days. Although that, you should be able to run the Strategy successfully.

If you have a different path for your `magic-link.tsx` file, you should let that know to the strategy by custimizing the `magicLinkGeneration` object that the Strategy provides.

Check the image and let me know if it fixed your issue.
![Screen Shot 2023-09-20 at 20 03 07](https://github.com/dev-xo/remix-auth-otp/assets/82425492/3899bf41-dd89-4ca0-8fe1-85e646865675)

**Comment by andersr** [comment]
@dev-xo Thanks for advice!  I think I am going to wait for the next version to come out and then revisit this.

**Comment by dev-xo** [comment]
Sounds good to me @andersr. 
In any case gonna look into it. Everything should go as expected with the current v2 version.

Closing this for now, feel free to comment here anything else about this topic.
