### ISSUE TITLE
[ Solved ] Package is no longer deprecated.

### ISSUE THREAD

**Issue by gavry** [dev-xo/remix-auth-otp#3]
Hey! I just happened to be deploying this at the same time you updated the package. Just checking - did you mean to change the name of the package from remix-auth-otp to "remix-auth-otp-latest"? Just double checking before I switch the package names in my repo! Thanks!

**Comment by dev-xo** [comment]
Hello @gavry !
Sorry for the inconveniences.

I've deprecated the whole package by mistake, so until tomorrow (24hours) we will have to use `remix-auth-otp-latest`.
Gonna try to update the Docs as fast as possible!.

🤦

**Comment by gavry** [comment]
No problem at all - thanks for a great package! Will do for now.

**Comment by dev-xo** [comment]
The new `remix-auth-otp-latest` should be available in a few minutes.
But I would recommend wait 1 hour or so, until I update the Docs with the newly security updates.

Thank you for understanding it!

**Comment by dev-xo** [comment]
Once again sorry for the inconveniences @gavry !

In your case, I would wait until tomorrow or 24 hours until now.
The v1.10.0 will get a security update against brute forcing. So yeah..

In any case, feel free to test the current v1.0.9 at `remix-auth-otp-latest`.

_(What a mess I did, we should not drink and code, will end bad 🙂)_

**Comment by dev-xo** [comment]
Gonna leave this Issue open, maybe could help someone else.

**Comment by dev-xo** [comment]
Solved @gavry !
Feel free to try the `v2.0.0`.

The deployed template example will be updated today.
The Docs has been already updated.

Feel free to comment me any other thing, and sorry for the inconveniences!
