### ISSUE TITLE
Expose `request` to `sendCode` and `verify`

### ISSUE THREAD

**Issue by w00fz** [dev-xo/remix-auth-otp#4]
Thanks for this library, I have something similar implemented but like yours better!

The only thing I am missing from this library is being able to access the `Request` object from the `sendCode` and `verify` functions. 

I want to be able to get to the `URL` because alongside the OTP code, I also want to send a magic link in the email. This way the user can either copy/paste the OTP code or click the magic link.

I believe this change would require exposing `request` in just these 3 instances (I can of course PR this if you like):

https://github.com/dev-xo/remix-auth-otp/blob/7ec9af5fcb6723876dd8d93cfc72592b1ddeabc8/src/index.ts#L336-L337
https://github.com/dev-xo/remix-auth-otp/blob/7ec9af5fcb6723876dd8d93cfc72592b1ddeabc8/src/index.ts#L396-L409

PS: Maybe the magic link is also something your library could provide as a built-in feature, if you are looking for ideas!

**Comment by dev-xo** [comment]
Got you @w00fz !
I've been using before a Magic Link Strategy, and I understand what you'r saying.

Could you please share your implementation with me _(from your own library)_?
So just exposing the Request object should be enought?

Again, thank you for reaching on here.
I would like to improve the library, and this seems like a good feature to be exposed.

**Comment by w00fz** [comment]
Hey @dev-xo,

I started a lengthly reply and quickly realized I could have just started a PR, so I did (#5).

Let me know what you think.

**Comment by dev-xo** [comment]
Checking it right now @w00fz ! It's simply brilliant!

You will hear from me soon!
I'm speechless!

**Comment by dev-xo** [comment]
Reach me on discord please, or give me your user ID, for a faster communication.
I'm dev-xo#9732 on Remix Discord.

**Comment by dev-xo** [comment]
Closing this @w00fz !
Again, thank you for the amazing PR and the incredible work you did in absolute no time!
