### ISSUE TITLE
fix: magic-link URL protocol for localhost

### ISSUE THREAD

**Issue by dev-xo** [dev-xo/remix-auth-otp#6]
Currently the protocol that reaches the email on localhost seems to be `https` instead of `http`.

**Comment by w00fz** [comment]
This shouldn't be happening, what did I do wrong?

https://github.com/dev-xo/remix-auth-otp/blob/fff3628fa78b428e73bf29c57a85e08dea2c3be6/src/utils.ts#L60-L64

**Comment by leimantas** [comment]
Maybe it would be safer to set some BASE_URL env and pass it as variable?

**Comment by dev-xo** [comment]
Fixed @leimantas!
Merging right now! 🎉
